version: '3.8'
services:
  db:
    image: postgres:15.1-alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=timesheets
    ports:
      - '9000:5432'