spring:
  datasource:
    url: jdbc:mysql://localhost:3306/timesheets?createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: admin
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          ddl-auto: none
          show-sql: true
  liquibase:
    changelog: classpath:db/changelog.yml

timesheets:
  statistics:
    time-interval: 60
    overtime-pay-ratio: 1.5
    holiday-pay-ratio: 2.0
    working-days: 5
  jwt:
    accessTokenValidityTime: 600000
    accessTokenSecret: 'ACCESS_TOKEN_SECRET_TO_CHANGE'
    refreshTokenValidityTime: 600000
    refreshTokenSecret: 'REFRESH_TOKEN_SECRET_TO_CHANGE'
